package cc.duduhuo.util.pojo.derivation.compiler.builder

import cc.duduhuo.util.pojo.derivation.compiler.DerivationLib
import cc.duduhuo.util.pojo.derivation.compiler.TargetClass
import com.bennyhuo.aptutils.utils.writeToFile
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec
import javax.lang.model.element.Modifier


/**
 * =======================================================
 * Author: liying - liruoer2008@yeah.net
 * Datetime: 2019/1/24 22:16
 * Description:
 * Remarks:
 * =======================================================
 */
class TargetClassBuilder(
    private val targetClass: TargetClass,
    private val derivationLib: DerivationLib
) {

    fun build() {

        val targetClassBuild = TypeSpec.classBuilder(targetClass.simpleName).addModifiers(Modifier.PUBLIC)

        val fieldSpecs = derivationLib.fieldList.values.map {
            it.spec
        }
        targetClassBuild.addFields(fieldSpecs)
        targetClassBuild.addMethods(derivationLib.methodList)
        val javaFile = JavaFile.builder(targetClass.packageName, targetClassBuild.build())
            .addFileComment(
                "This file is automatically generated by pojo-derivation (https://github.com/liying2008/pojo-derivation).\n" +
                        "Do not modify this file -- YOUR CHANGES WILL BE ERASED!"
            )
            .build()
        javaFile.writeToFile()
    }
}